#!/usr/bin/env python
# coding: utf-8

# In[48]:


import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns





# In[49]:


lm= pd.read_csv(r"C:\Users\Hardik\Downloads\data.csv",encoding=('ISO-8859-1'),low_memory =False)


# In[50]:


lm.head(1)


# In[51]:


lm.shape


# # Checking Null Values
# 

# In[52]:


print("\nNull Values:\n", lm.isnull().sum())


# # Checking Missing Values
# 

# In[53]:


print("\nMissing Values:\n", lm.isna().sum())


# # Information of data
# 

# In[54]:


lm.info()


# # Statistical Description of Data
# 

# In[55]:


lm.describe()


# # Extracting Mean, Squared Error and Worst Features with Diagnosis
# 

# In[56]:


lm_mean = lm[lm.columns[:11]]
lm_se = lm.drop(lm.columns[1:11], axis=1);
lm_se = lm_se.drop(lm_se.columns[11:], axis=1)
lm_worst = lm.drop(lm.columns[1:21], axis=1)


# Count Based On Diagnosis
# 

# In[57]:


lm.diagnosis.value_counts()


# In[58]:


lm.diagnosis.value_counts() \
    .plot(kind="bar", width=0.1, color=["lightgreen", "cornflowerblue"], legend=1, figsize=(8, 5))
plt.xlabel("(0 =  Benign) (1 =Malignant)", fontsize=12)
plt.ylabel("Count", fontsize=12)
plt.xticks(fontsize=12);
plt.yticks(fontsize=12)
plt.legend([" Benign"], fontsize=12)
plt.show()


# Correlation with diagnosis:

# In[59]:


def corrwithdia(lmx):
    import matplotlib.pyplot as plt
    name = str([x for x in globals() if globals()[x] is lmx][0])
    if name == 'lm':
        x = "All"
    elif name == 'lm_mean':
        x = "Mean"
    elif name == 'lm_se':
        x = "Squared Error"
    elif name == 'lm_worst':
        x = "Worst"
    plt.figure(figsize=(20, 8))
    lmx.drop('diagnosis', axis=1).corrwith(lmx.diagnosis).plot(kind='bar', grid=True, title="Correlation of {} Features with Diagnosis".format(x), color="cornflowerblue");


# correlation of Mean Features with Diagnosis
# 

# In[60]:


corrwithdia(lm_mean)


# Correlation of Squared Error Features with Diagnosis
# 

# In[61]:


corrwithdia(lm_se)


# Correlation of Worst Features with Diagnosis
# 

# In[62]:


corrwithdia(lm_worst)


# Extracting Mean, Squared Error and Worst Features

# In[63]:


lm_mean_cols = list(lm.columns[1:11])
lm_se_cols = list(lm.columns[11:21])
lm_worst_cols = list(lm.columns[21:])


# Split into two Parts Based on Diagnosis

# In[64]:


lmM = lm[lm['diagnosis'] == 1]
lmB = lm[lm['diagnosis'] == 0]


# Nucleus Mean Features vs Diagnosis

# In[65]:


plt.rcParams.update({'font.size': 8})
fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(8, 10))
axes = axes.ravel()
for idx, ax in enumerate(axes):
    ax.figure
    binwidth = (max(lm[lm_mean_cols[idx]]) - min(lm[lm_mean_cols[idx]])) / 50
    ax.hist([lmM[lm_mean_cols[idx]], lmB[lm_mean_cols[idx]]],
            bins=np.arange(min(lm[lm_mean_cols[idx]]), max(lm[lm_mean_cols[idx]]) + binwidth, binwidth), alpha=0.5,
            stacked=True, label=['M', 'B'], color=['b', 'g'])
    ax.legend(loc='upper right')
    ax.set_title(lm_mean_cols[idx])
plt.tight_layout()
plt.show()


# Nucleus Squared Error Features vs Diagnosis

# In[66]:


plt.rcParams.update({'font.size': 8})
fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(8, 10))
axes = axes.ravel()
for idx, ax in enumerate(axes):
    ax.figure
    binwidth = (max(lm[lm_se_cols[idx]]) - min(lm[lm_se_cols[idx]])) / 50
    ax.hist([lmM[lm_se_cols[idx]], lmB[lm_se_cols[idx]]],
            bins=np.arange(min(lm[lm_se_cols[idx]]), max(lm[lm_se_cols[idx]]) + binwidth, binwidth), alpha=0.5,
            stacked=True, label=['M', 'B'], color=['b', 'g'])
    ax.legend(loc='upper right')
    ax.set_title(lm_se_cols[idx])
plt.tight_layout()
plt.show()


# Nucleus Worst Features vs Diagnosis

# In[67]:


plt.rcParams.update({'font.size': 8})
fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(8, 10))
axes = axes.ravel()
for idx, ax in enumerate(axes):
    ax.figure
    binwidth = (max(lm[lm_worst_cols[idx]]) - min(lm[lm_worst_cols[idx]])) / 50
    ax.hist([lmM[lm_worst_cols[idx]], lmB[lm_worst_cols[idx]]],
            bins=np.arange(min(lm[lm_worst_cols[idx]]), max(lm[lm_worst_cols[idx]]) + binwidth, binwidth), alpha=0.5,
            stacked=True, label=['M', 'B'], color=['b', 'g'])
    ax.legend(loc='upper right')
    ax.set_title(lm_worst_cols[idx])
plt.tight_layout()
plt.show()


# Checking Multicollinearity Between Different Features

# In[68]:


def pairplot(lmx):
    import seaborn as sns
    name = str([x for x in globals() if globals()[x] is lmx][0])
    if name == 'lm_mean':
        x = "Mean"
    elif name == 'lm_se':
        x = "Squared Error"
    elif name == 'lm_worst':
        x = "Worst"
    sns.pairplot(data=lmx, hue='diagnosis', palette='crest', corner=True).fig.suptitle('Pairplot for {} Featrues'.format(x), fontsize = 20)


# # Mean Features:
# 
# 

# In[69]:


pairplot(lm_mean)


# Squared Error Features:
# 
# 

# In[70]:


pairplot(lm_se)


# Worst features:
# 
# 

# In[71]:


pairplot(lm_worst)


# # Correlation Heartmap between Nucleus Feature

# In[72]:


corr_matrix = lm.corr()  

mask = np.zeros_like(corr_matrix, dtype=np.bool_)
mask[np.triu_indices_from(corr_matrix)] = True

fig, ax = plt.subplots(figsize=(22, 10))
ax = sns.heatmap(corr_matrix, mask=mask, annot=True, linewidths=0.5, fmt=".2f", cmap="YlGn");
bottom, top = ax.get_ylim()
ax.set_ylim(bottom + 0.5, top - 0.5);
ax.set_title("Correlation Matrix Heatmap including all features");


# Outliers

# In[73]:


for column in lm:
    plt.figure()
    lm.boxplot([column])
    plt.show()


# Outlier removal

# In[74]:


from numpy import percentile
for column in lm.columns:
    q25, q75 = percentile(lm[column], 25), percentile(lm[column], 75)
    iqr = q75 - q25
    print('Percentiles: 25th=%.3f, 75th=%.3f, IQR=%.3f' % (q25, q75, iqr))
    cut_off = iqr * 1.5
    lower, upper = q25 - cut_off, q75 + cut_off
    outliers = [x for x in lm[column] if x < lower or x > upper]
    print('Identified outliers: %d' % len(outliers))
    outliers_removed = [x for x in lm[column] if x >= lower and x <= upper]
    print('Non-outlier observations: %d' % len(outliers_removed))
    lm = lm[lm[column] < upper]
    plt.figure()
    lm.boxplot([column])
    plt.show()


# In[ ]:




